a=3
b=2
op_adicao=a+b
print( "Adição -> ",a,"+" , b, "=" ,op_adicao)
op_subtracao=a-b
print("Subtração -> ",a,"-", b, "=" , op_subtracao)
op_multiplicacao=a*b
print ("Multiplícação ->" ,a,"X" ,b,"=" , op_multiplicacao)
op_divisao=a/b
print( "Divisão -> ",a," / ",b,"=",op_divisao)
op_divisao_int=a//b
print ( "Divisão inteira ->",a,"//",b,"=",op_divisao_int)
op_modulo_div=a%b
print ("Módulo -> 11 ",a,"%", b, "=" , op_modulo_div)
op_exponenciacao=a**b
print ("Exponenciação ->" ,a, "**" , b,"=" , op_exponenciacao)